---
# Adhering to the declarative paradigm, this configures a 
# managed server, specifically an AWS EC2 instance. Tasks include 
# package installation, cache update, SQL query execution, etc.

# A playbook is a list of one or more plays
# A play defines a list of tasks
- name: Configure backend (AWS EC2 instance target host for app - backend and frontend)
  hosts: managed_app_node
  become: true

  tasks:
    # The debug module print a message on the terminal for debugging purpose
    - name: Print success message
      debug: 
        msg: "The control node successfully ran the backend playbook."