---
# This playbook is executed second and configures Apache to serve a web page
# explaining the purpose of this EC2 instance, which acts as a control node
# for executing Ansible configurations on other virtual machines.

- name: Configure control node
  hosts: control_node
  become: true
  tasks:
    - name: Install Apache web server
      package:
        name: httpd
        state: present
        
    - name: Copy HTML template file to control node
      copy:
        src: ../../roles/control_node/templates/index.html.j2
        dest: /var/www/html/index.html
        mode: "0644"
      notify: Restart Apache   # If necessary, restart the web server after copying the HTML file

    - name: Ensure Apache service is running and enabled
      service:
        name: httpd
        state: started
        enabled: yes
