name: Ansible CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      # - name: Install dependencies
      #   run: pip install ansible

      # - name: Install Ansible
      #   run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Install dependencies
        run: |
          pip install --upgrade ansible
          pip install --upgrade ansible-lint

      # - name: Configure aws credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-region: ${{ secrets.AWS_REGION }}
      #     role-to-assume: ${{ secrets.ROLE_ASSUME }}

      - name: Install Ansible-Galaxy Requirements
        run: ansible-galaxy install -r ansible/requirements.yml

      - name: Test and validate Ansible playbooks
        run: ansible-lint --exclude fqcn --exclude-path '*/roles/*' ansible/playbooks/control_node/configure_control_node.yml


      - name: Run Ansible playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/playbooks/control_node/control_node.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: Execute Ansible playbook
      #   uses: ansible/ansible-playbook-action@v2
      #   with:
      #     playbook: path/to/your/playbook.yml
      #     inventory: path/to/your/inventory
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
