# TODO: - Move to roles

- name: Include vars files dynamically
  include_vars:
    file: "{{ item }}"
  loop:
    - ../vars/managed_db_node/secret.yml
    - ../../host_groups/managed_app_node/vars.yml # FIXME: shouldn't be necessary

- name: Ensure directory exists for todo.env
  file:
    path: /etc
    state: directory

- name: Ensure todo.env file exists
  file:
    path: "{{ be_env_file }}"
    state: touch

# - name: Env file exists
#   file:
#     path: "{{ be_env_file }}"
#     state: file

# Populate DB_NAME in todo.env
- name: Update DB_NAME in todo.env
  lineinfile:
    path: "{{ be_env_file }}"
    line: DB_NAME={{ db_name_todo }}
    regexp: '^DB_NAME='

# Populate DB_CONNECTION in todo.env
- name: Update DB_CONNECTION in todo.env
  lineinfile:
    path: "{{ be_env_file }}"
    # line: mongodb://username:password@host:port/database
    line: DB_CONNECTION=mongodb://{{ db_todo_user }}:{{ db_todo_pass }}@{{ hostvars[groups['managed_db_node'][0]]['ansible_default_ipv4']['address'] }}:27017
    regexp: '^DB_CONNECTION='