# TODO: - Move to roles

- name: Include vars file dynamically
  include_vars:
    file: ../vars/managed_db_node/secret.yml

- name: env file exists
  file:
    path: "{{ be_env_file }}"
    state: file

# Populate  DB_NAME
- name: DB_NAME env var is up-to-date
  lineinfile:
    path: "{{ be_env_file }}"
    line: DB_NAME={{ db_name_todo }}
    regexp: '^DB_NAME='

# Populate DB_CONNECTION
- name: DB_CONNECTION env var is up-to-date
  lineinfile:
    path: "{{ be_env_file }}"
    line: DB_CONNECTION=mongodb://{{ db_todo_user }}:{{ db_todo_pass }}@{{ groups['managed_db_node']['ansible_facts']['default_ipv4']['address'] }}:27017
    regexp: '^DB_CONNECTION='